version: "3"
services:
  nginx:
    image: nginx:1.15.7-alpine
    container_name: nginx1.15
    ports:
      - "80:80"
    volumes:
    # /Users/Pie/www/   /Users/Pie/docker-lnmp/ 均为宿主目录，根据实际情况修改
      - /Users/Pie/www/:/var/www/html/:rw
      - /Users/Pie/docker-lnmp/conf/nginx/:/etc/nginx/:rw
      - /Users/Pie/docker-lnmp/log/nginx/:/var/log/nginx/:rw
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - default

  php:
    build: .
    container_name: php7.2
    volumes:
      - /Users/Pie/www/:/var/www/html/:rw
      - /Users/Pie/docker-lnmp/conf/php/:/usr/local/etc/php/:rw
      - /Users/Pie/docker-lnmp/conf/php-fpm.d/:/usr/local/etc/php-fpm.d/:rw
      - /Users/Pie/docker-lnmp/log/:/var/log/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    ports:
      - "3306:3306"
    volumes:
      - /Users/Pie/docker-lnmp/conf/mysql/:/etc/mysql/:rw
      - /Users/Pie/docker-lnmp/mysql/data/:/var/lib/mysql/:rw
      #- /Users/Pie/docker-lnmp/log/:/var/log/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "mysql1810"
      TZ: "Asia/Shanghai"

  redis:
    image: redis:5.0.10
    container_name: redis5.0.10
    ports:
      - "6379:6379"
    volumes:
      - /Users/Pie/docker-lnmp/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
    restart: always
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - default

  rabbitmq:
    #use docker images
    image: rabbitmq:3.8.14-management-alpine
    container_name: rabbitmq3.8.14
    #setup host name
    hostname: rabbitmq3.8.14
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    # /Users/Pie/www/   /Users/Pie/docker-lnmp/ 均为宿主目录，根据实际情况修改
      - /Users/Pie/docker-lnmp/db_data/rabbitmq/:/var/lib/rabbitmq/:rw
      - /Users/Pie/docker-lnmp/log/rabbitmq/:/var/log/rabbitmq/:rw
    environment:
      #设置后台登录用户和密码，没设置默认为：guest/guest
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "rabbitmq1810"
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - default

  mongodb:
    #use docker images
    image: mongo:4.2
    container_name: mongodb4.2
    ports:
      #使用默认的 MongoDB 端口 27017 到 27019
      - "27017-27019:27017-27019"
    volumes:
    # /Users/Pie/www/   /Users/Pie/docker-lnmp/ 均为宿主目录，根据实际情况修改
      - /Users/Pie/docker-lnmp/conf/mongodb/mongod.conf:/etc/mongod.conf:rw
      - /Users/Pie/docker-lnmp/db_data/mongodb/:/data/db/:rw
      - /Users/Pie/docker-lnmp/log/mongodb/:/var/log/mongodb/:ro
      - /Users/Pie/docker-lnmp/db_data/mongodb/mongo-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:rw
    environment:
      #设置后台登录用户和密码，没设置默认为：guest/guest
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "mongodb1810"
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - default

networks:
  default:
